version: '3'
services:
  app:
    image: golang:1.22.5-alpine
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/auth/main.go
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/testingDB?sslmode=disable
      - JWT_SECRET=123123123
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=testingDB
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
   
